# **MinMaxScaler**

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = [[3, 2], [15, 6], [0, 10], [1, 18]]

In [3]:
scaler = MinMaxScaler()
print(scaler.fit(data))

MinMaxScaler()


In [4]:
print(scaler.data_max_)

[15. 18.]


In [5]:
print(scaler.data_min_)

[0. 2.]


In [6]:
print(scaler.transform(data))

[[0.2        0.        ]
 [1.         0.25      ]
 [0.         0.5       ]
 [0.06666667 1.        ]]


# **StandardScaler**

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
data = [[3, 2], [15, 6], [0, 10], [1, 18]]

In [12]:
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler()


In [13]:
print(scaler.mean_)

[4.75 9.  ]


In [14]:
print(scaler.transform(data))

[[-0.29091007 -1.18321596]
 [ 1.70390185 -0.50709255]
 [-0.78961305  0.16903085]
 [-0.62337873  1.52127766]]


# **Log Scaler**

In [15]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [16]:
data = np.array([[0,1], [2,3]])

In [17]:
transformer = FunctionTransformer(np.log1p)

In [18]:
print(transformer.transform(data))

[[0.         0.69314718]
 [1.09861229 1.38629436]]


# **MaxAbsScaler**

In [19]:
from sklearn.preprocessing import MaxAbsScaler

In [24]:
data = [[ 1., -1.,  2.],
        [ 2.,  0.,  0.],
        [ 0.,  1., -1.]]

In [25]:
scaler = MaxAbsScaler()
print(scaler.fit(data))

MaxAbsScaler()


In [26]:
print(scaler.max_abs_)

[2. 1. 2.]


In [27]:
print(scaler.transform(data))

[[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]


# **RobustScaler**

In [28]:
from sklearn.preprocessing import RobustScaler

In [29]:
data = [[ 1., -2.,  2.],
        [ -2.,  1.,  3.],
        [ 4.,  1., -2.]]

In [30]:
scaler = RobustScaler()
print(scaler.fit(data))

RobustScaler()


In [33]:
print(scaler.center_)

[1. 1. 2.]


In [34]:
print(scaler.transform(data))

[[ 0.  -2.   0. ]
 [-1.   0.   0.4]
 [ 1.   0.  -1.6]]


# **Normalizer**

In [35]:
from sklearn.preprocessing import Normalizer

In [43]:
data = [[4, 1, 2, 2],
        [1, 3, 9, 3],
        [5, 7, 5, 1]]

In [48]:
trans_l1 = Normalizer(norm='l1')
trans_l2 = Normalizer()
trans_max = Normalizer(norm='max')
print(trans_l1.fit(data))
print(trans_l2.fit(data))
print(trans_max.fit(data))

Normalizer(norm='l1')
Normalizer()
Normalizer(norm='max')


In [49]:
print(trans_l1.transform(data))

[[0.44444444 0.11111111 0.22222222 0.22222222]
 [0.0625     0.1875     0.5625     0.1875    ]
 [0.27777778 0.38888889 0.27777778 0.05555556]]


In [50]:
print(trans_l2.transform(data))

[[0.8 0.2 0.4 0.4]
 [0.1 0.3 0.9 0.3]
 [0.5 0.7 0.5 0.1]]


In [51]:
print(trans_max.transform(data))

[[1.         0.25       0.5        0.5       ]
 [0.11111111 0.33333333 1.         0.33333333]
 [0.71428571 1.         0.71428571 0.14285714]]
